import 'package:flutter/material.dart';
Color grey = const Color(0xff4F5C74);
Color blueForButton = const Color(0xff0D70E3);
Color blueForButtonDisabled = const Color(0x560D70E3);
Color bottomNavBarBackground = const Color(0x81F1F1F1);
Color unselectedItem = const Color(0xff8F98A8);
Color selectedItem = const Color(0xff231F20);
Color contentBackground = const Color(0xffF7F7F7);
Color lightGrey = const Color(0xff8F98A8);
Color secondaryBlue = const Color(0xff0DB0E3);
